apiVersion: v1
kind: Service
metadata:
  name: bodo-tabpy
  namespace: bodo 
  labels:
    app: bodo-tabpy
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: bodo-tabpy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bodo-tabpy
  namespace: bodo
  labels:
    app: bodo-tabpy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bodo-tabpy
  template:
    metadata:
      labels:
        app: bodo-tabpy
    spec:
      containers:
      - name: bodo-tabpy
        image: tfoldi/bodo-ipp-tabpy
        env:
         - name: SNOWFLAKE_URL
           valueFrom:
             secretKeyRef:
               name: snowflake-url
               key: SNOWFLAKE_URL  
        ports:
        - containerPort: 8080
  